### ISSUE TITLE
xdem 0.0.13 does not work with geoutils 0.0.13

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/xdem#399]
Geoutils [commit 24a1ab7](https://github.com/GlacioHack/geoutils/pull/385) (which is now part of gu 0.0.13) removed the type `AnyNumber` from `geoutils._typing`. xdem 0.0.13 tries to import this, leading to an import failure:

```python

>>> import xdem
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
File /nix/store/pb6r2m9kjij7yp1s1b453fbdny8ffjac-python3-3.10.10-env/lib/python3.10/site-packages/xdem/__init__.py:1, in <module>
----> 1 from xdem import (  # noqa
      2     coreg,
      3     dem,
      4     examples,
      5     filters,
      6     fit,
      7     spatialstats,
      8     terrain,
      9     volume,
     10 )
     11 from xdem.ddem import dDEM  # noqa
     12 from xdem.dem import DEM  # noqa

File /nix/store/pb6r2m9kjij7yp1s1b453fbdny8ffjac-python3-3.10.10-env/lib/python3.10/site-packages/xdem/coreg/__init__.py:5, in <module>
      1 """
      2 DEM coregistration classes and functions, including affine methods, bias corrections (i.e. non-affine) and filters.
      3 """
----> 5 from xdem.coreg.affine import (  # noqa
      6     ICP,
      7     AffineCoreg,
      8     GradientDescending,
      9     NuthKaab,
     10     Tilt,
     11     VerticalShift,
     12 )
     13 from xdem.coreg.base import BlockwiseCoreg, Coreg, CoregPipeline, apply_matrix  # noqa
     14 from xdem.coreg.biascorr import (  # noqa
     15     BiasCorr,
     16     BiasCorr1D,
   (...)
     21     TerrainBias,
     22 )

File /nix/store/pb6r2m9kjij7yp1s1b453fbdny8ffjac-python3-3.10.10-env/lib/python3.10/site-packages/xdem/coreg/affine.py:25, in <module>
     22 from tqdm import trange
     24 from xdem._typing import NDArrayf
---> 25 from xdem.coreg.base import (
     26     Coreg,
     27     CoregDict,
     28     _get_x_and_y_coords,
     29     _mask_dataframe_by_dem,
     30     _residuals_df,
     31     _transform_to_bounds_and_res,
     32     deramping,
     33 )
     34 from xdem.spatialstats import nmad
     36 try:

File /nix/store/pb6r2m9kjij7yp1s1b453fbdny8ffjac-python3-3.10.10-env/lib/python3.10/site-packages/xdem/coreg/base.py:38, in <module>
     36 import scipy.optimize
     37 import skimage.transform
---> 38 from geoutils._typing import AnyNumber
     39 from geoutils.raster import (
     40     Mask,
     41     RasterType,
   (...)
     45     subsample_array,
     46 )
     47 from tqdm import tqdm

ImportError: cannot import name 'AnyNumber' from 'geoutils._typing' (/nix/store/pb6r2m9kjij7yp1s1b453fbdny8ffjac-python3-3.10.10-env/lib/python3.10/site-packages/geoutils/_typing.py)
```

The only current workaround is to downgrade to geoutils 0.0.12, whereby everything seems to work.

The fix is to replace `AnyNumber` in `xdem/coreg/base.py` (and potentially other places) to whatever it's supposed to be called. @rhugonnet, could you have a look at this?

**Comment by rhugonnet** [comment]
Fixed! :wink:

**Comment by erikmannerfelt** [comment]
Thanks for the quick fix! But I need to reopen because both the pypi and conda-forge builds still have this problem (since it's not the main branch, but the original 0.0.13 release).

There are two solutions for this:

- Mark a 0.0.14 release
- Do a second 0.0.13 build (but that would also include all commits on main since the original 0.0.13).

This is why we should move to a "major.minor.patch" versioning I think. This could have been 0.13.1; a patch of 0.13.0.

What do you think of the two solutions in the meantime, @rhugonnet , @adehecq ?

**Comment by adehecq** [comment]
Yes, moving to a "major.minor.patch" versioning makes sense. A lot of changes are made to geoutils and xdem at the moment which causes some interdependancy issues...
In the meantime, I think it's fine to do a second 0.0.13 build, but can we actually overwrite the previous one? I think it will fail. Or did I misunderstand?

**Comment by rhugonnet** [comment]
I agree for "major.minor.patch". 
In terms of defining what those mean:
- For "major":, I think it makes sense to have a stable `1.0` once we reach absolutely all base features, don't want to go too fast on those (NumPy is still `1.25`, for instance and Pandas just reached `2.0`; I don't see a `2.0` for xDEM coming before many many years),
- For "minor": Everything else that introduces a new significant change is a "minor" (new feature or behaviour change),
- For "patch": Everything that simply corrects a behaviour or feature or development.

For xDEM, we could:
- Release a `0.1` once the empty doc pages are filled,
- Release a `0.2` once the new co-registration is finalized,
- Release a `0.3` once the Xarray accessor is finalized,
- After feedback from colleagues, test improvement, etc... release `1.0`?! :smile:

**Comment by erikmannerfelt** [comment]
> I agree for "major.minor.patch". In terms of defining what those mean:
> 
>     * For "major":, I think it makes sense to have a stable `1.0` once we reach absolutely all base features, don't want to go too fast on those (NumPy is still `1.25`, for instance and Pandas just reached `2.0`; I don't see a `2.0` for xDEM coming before many many years),
> 
>     * For "minor": Everything else that introduces a new significant change is a "minor" (new feature or behaviour change),
> 
>     * For "patch": Everything that simply corrects a behaviour or feature or development.
> 
> 
> For xDEM, we could:
> 
>     * Release a `0.1` once the empty doc pages are filled,
> 
>     * Release a `0.2` once the new co-registration is finalized,
> 
>     * Release a `0.3` once the Xarray accessor is finalized,
> 
>     * Potentially other "minor"...
> 
>     * After feedback from colleagues, test improvement, etc... release `1.0`?! smile
> 
> 
> What do you think @erikmannerfelt @adehecq?

Yes that's great! Somewhere I've read that major versions are usually defined as API breaking, meaning it's almost certain that all post- and pre-version user-side code will have to be rewritten. As long as we're not introducing API breaking stuff, there might not even be a reason to go 1.x.

**Comment by erikmannerfelt** [comment]
> I don't think this is a problem, because xdem `0.0.11` to `0.0.13`'s environment dependency is `geoutils==0.0.12`, so everything works perfectly when building or updating the environment on conda (and we don't want/recommend to do that with pip, as it is likely to break other geospatial dependencies).
> 
> The current change in xdem can be released as a `0.0.14` (now or later), which will work with `geoutils==0.0.13`. So there's currently no occurence where the conda build fails for users (and pulling `main` now works for developers too).
> 
> So it's just a "pip" problem? We never specified the dependencies there anyway, I think? Should we start doing it?

Should we just work toward a 0.0.14 release then and pretend like this problem doesn't exist? I added quite many issues in the last few days which I intend to solve (maybe next week). Then this would solve itself!
